### ISSUE TITLE
No module named 'talib'

### ISSUE THREAD

**Issue by DolevAlgam** [otassel/docker-python-talib#1]
Hey,
When using the alpine version I can import talib easily and see it when running pip list.
However, when using the full version, which I need, talib doesn't show up when running pip list and isn't found when using import talib.

Thank you in advance :)

**Comment by otassel** [comment]
Hi Dolev,
Can you post here logs when you tried to install the library?

**Comment by mygithubkas** [comment]
Hi Olivier,
I spent the whole weekend and can't get Talib to run with python in Docker. 
I included your code snippet (below) in my dockerfile and ran a build.

RUN wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz && \
  tar -xvzf ta-lib-0.4.0-src.tar.gz && \
  cd ta-lib/ && \
  ./configure --prefix=/usr && \
  make && \
  make install

My image seems to build successfully:  Successfully tagged myfunction:latest
but when I run docker run, I get following:

>import talib
ModuleNotFoundError: No module named 'talib'

Any tips my friend ?
Thank you,
Kas

**Comment by otassel** [comment]
Seems to be closed
